### ISSUE TITLE
New Deaths Summary Program

### ISSUE THREAD

**Issue by rpitingolo** [NeighborhoodInfoDC/Vital#24]
@maggiesu0725 can you please set up a program similar to Births_sum_all_address.sas for the death data? Thanks!

**Comment by ptatian** [comment]
@rpitingolo @maggiesu0725 Please include the 1998 - 2002 death data in the summary files, too. Even though it's older data, we should still use it (unless there's some reason not to). 

Similar for the birth summaries. Can we please update those programs as well? Thank you.

**Comment by ptatian** [comment]
@rpitingolo Ah, yes. I forgot that. Makes sense to tackle that later, then. Thanks!

**Comment by rpitingolo** [comment]
@ptatian in theory it's not hard, the trouble is that %Create_all_summary_from_tracts requires a file called [name]_tr10 as the input, so I think we basically need to save a legacy version of deaths_sum_tr10 to feed into the macro. But I don't want to call it deaths_sum_tr10 because that would  get confusing with all of the other deaths_sum_[geo] variables that have newer data included.

**Comment by ptatian** [comment]
@rpitingolo I was just reminded by a question that @maggiesu0725 asked me that we should apply the **suppr5f.** format to the variables in the births and deaths summary data sets, as we do with the TANF and food stamp files. Our agreement with DOH requires us to suppress cells where counts are less than 5. This format is already in the General library and so does not need to be created.

**Comment by rpitingolo** [comment]
@ptatian thanks, so that should be applied to the base data sets (and as a result the summary datasets)?

**Comment by rpitingolo** [comment]
@ptatian sorry, just the summary files. Obviously the suppression will depend on the geography in questino.

**Comment by ptatian** [comment]
@rpitingolo Yes, just the summary files.

**Comment by rpitingolo** [comment]
@ptatian Hi Peter. @maggiesu0725 pointed out that suppr5f. doesn't suppress zeros (if data = 0 it keeps it as 0). However it sounds like for IRB we are supposed to suppress everything less than 5 which I would interpret as including zero. Do you have a take on this?

**Comment by ptatian** [comment]
Zero means no one is there so you aren’t revealing any information about anyone.

**Comment by lhendey** [comment]
@rpitingolo @maggiesu0725 - can this issue be closed?

**Comment by rpitingolo** [comment]
@lhendey yes
