### ISSUE TITLE
Summarize birth data for ODCA study

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/Vital#9]

**Comment by rpitingolo** [comment]
@maggiesu0725 the problem was that there was a syntax error in your proc sort. I fixed that and got everything to run, but unfortunately it looks like a quarter of the records didn't spatially merge correctly. I don't know enough about proc ginside to diagnose beyond that.

**Comment by lhendey** [comment]
@ptatian review this issue

**Comment by ptatian** [comment]
@lhendey @rpitingolo @maggiesu0725 FYI, when you want a review you should make a pull request.

**Comment by ptatian** [comment]
@lhendey @rpitingolo @maggiesu0725 Sorry, I should have stated it more clearly. Someone should please make a pull request so that I can review. Thank you.
